### ISSUE TITLE
Assessments -- Save User Notes Endpoint

### ISSUE THREAD

**Issue by cwc-products** [intoCareers/cis-client-apis#57]
@Curtis Fuhriman I think if the goal here is to match the current api / UI functionality, we could provide an endpoint for this.

Currently the UI allows users to submit notes supported by the following API endpoint:

<img width="541" alt="screen shot 2018-11-21 at 2 35 01 pm" src="https://user-images.githubusercontent.com/6207328/48871687-a4c63600-ed9a-11e8-8ec4-4e0b9bdbec99.png">

**Comment by intoCareers** [comment]
There is also the /users/saveUserNotes/ call for a completed assessment.

**Comment by cwc-products** [comment]
@rajesh-tammina I have pushed the stubbed out changes to https://qa.services.intocareers.net/swagger/assessments-ability-explorer#/.  Here are a few questions I have for you thinking about this from a UI perspective.

- [ ] Should the POST /api/v1/assessment/ae/save (https://services.intocareers.net/swagger/assessments-ability-explorer#/Scoring/post_api_v1_assessment_ae_save) and other save / score endpoints accept notes with the answers?

- [ ] Should GET /api/v1/assessment/ae/list (https://services.intocareers.net/swagger/assessments-ability-explorer#/History/get_api_v1_assessment_ae_list) return the notes?

**Comment by cwc-products** [comment]
Stubbed out changes in #63.

**Comment by muralidhar-chintada** [comment]
> @rajesh-tammina I have pushed the stubbed out changes to https://qa.services.intocareers.net/swagger/assessments-ability-explorer#/. Here are a few questions I have for you thinking about this from a UI perspective.
> 
> * [ ]  Should the POST /api/v1/assessment/ae/save (https://services.intocareers.net/swagger/assessments-ability-explorer#/Scoring/post_api_v1_assessment_ae_save) and other save / score endpoints accept notes with the answers?

@cwc-products  yes . need not be separate call for this. Just key ,value pair in the existing save and score calls .

> * [ ]  Should GET /api/v1/assessment/ae/restore/from/{restoreKey} (https://services.intocareers.net/swagger/assessments-ability-explorer#/Scoring/get_api_v1_assessment_ae_restore_from__restoreKey_) return the notes for that restored assessment.

@cwc-products  yes . 

> * [ ]  Should GET /api/v1/assessment/ae/list (https://services.intocareers.net/swagger/assessments-ability-explorer#/History/get_api_v1_assessment_ae_list) return the notes?

@cwc-products  yes .

**Comment by cwc-products** [comment]
@muralidhar-chintada we're not fully implementing this for a few weeks.  I just wanted you to confirm that these stubbed out endpoints work to allow you to develop against.

**Comment by muralidhar-chintada** [comment]
@cwc-products Its working perfectly .
