### ISSUE TITLE
Ability Explorer -- Best Match

### ISSUE THREAD

**Issue by cwc-products** [intoCareers/cis-client-apis#62]
We need top2 abilities in the score api call, In the old Cis-AE  api once we can post the answers it's returns best match abilities , please see the screen shot for better understanding.

![unknown](https://user-images.githubusercontent.com/6207328/49112086-b306cd00-f246-11e8-8cb7-d245fc76f6a8.png)

For standalone AE api  doesn't returns abilities in the score call
 
POST/api/v1/assessment/ae/score

![unknown-1](https://user-images.githubusercontent.com/6207328/49112091-b69a5400-f246-11e8-9c6e-e97ff45fdfcd.png)

**Comment by cwc-products** [comment]
@rajesh-tammina please confirm you see the expected changes on production.

<img width="1332" alt="unknown-2" src="https://user-images.githubusercontent.com/6207328/49112133-d467b900-f246-11e8-9456-53c509061440.png">

**Comment by rajesh-tammina** [comment]
@cwc-products The changes are there in production.
